# https://taskfile.dev

version: "3"

vars:
  PYTHON_SRC: "address_etl"
  TESTS_DIR: "tests"

tasks:
  default:
    cmd: task -a
    silent: true

  dev:
    cmd: uv run main.py

  format:
    desc: Format Python code.
    cmds:
      - uv run ruff format $PYTHON_SRC
      - uv run ruff check --select I --fix $PYTHON_SRC
      - uv run ruff format $TESTS_DIR
      - uv run ruff check --select I --fix $TESTS_DIR

  code:
    desc: Alias of format.
    cmds:
      - task: format

  test:
    desc: Run the tests.
    cmds:
      - uv run pytest -rP
